### PR TITLE
General Cleanup + Some Styles + Cool Loading Spinner

### PR DESCRIPTION
**Pull request by oneezy**
Hey Alex,
Did a lot of clean up/ restructuring/ simplifying. Started by extracting the inline/inpage styles from the html/js and linked into an external stylsheet (css/stylesheet.css). Also re-did the leftside navigation for better style control, along with a few "soft" style tweaks. For the color choices on the cards, I'm using the Material Design visual guidelines spec from Google..it seems to fit in nicely with Trello's colors. Didn't touch any of the js logic or tackle any bugs. Just wanted to take it easy on this first go round.

There were a few more things I wanted to get in before I sent this initial pull request. There's a "FOUJ" (Flash Of Uninitialized Javascript) that shows in the navigation when clicking the show/hide dependencies. It can be fixed by using inline styles there or using a delayed css transition/animation. Also, the SVG spinner is acting up a bit (I believe it's from it not being pre-loaded and the animation can't keep up w/ the rest).

Everything seems to be looking good though.

### CODE REVIEW

**Comment by alexanderpreston** [comment]
Nice, I merged the pull request and it looks pretty good. Just a couple of bugs to fix on the Development board and I'll release v1.7!

**Comment by alexanderpreston** [comment]
https://trello.com/b/o2OGA28L/development

**Comment by oneezy** [comment]
niCe! I'll fix a few more things up and make another push this weekend

**Comment by alexanderpreston** [comment]
Hi Justin, How's it going?
Sorry for going dark, I had a few things with the business to attend to after getting back from holiday.
Did you have any luck with those bugs?

**Comment by alexanderpreston** [comment]
Hi @oneezy - are you on Skype?

**Comment by oneezy** [comment]
Hey Alex,Sorry been out of commission lately. Been out of town and not at a computer for awhile. i have a Skype but i use Google Hangouts mainly now.
I'll reach back out to you soon.

Sent from my Verizon Wireless 4G LTE smartphone

-------- Original message --------

**Pull request merged**
